const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
const src=fs.readFileSync('lib/outlook-server.ts','utf8');
const code=ts.transpileModule(src.slice(src.indexOf('export async function createOutlookDraft('),src.indexOf('export function outlookRequestOrigin')),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
function setup({scope='Mail.ReadWrite Mail.Send',attachmentFailure=false,sendStatus=202,networkFailure=false}={}){
 const calls=[];const deps={query:async()=>({rows:[{scope}]}),getOutlookAccessToken:async()=> 'test',createOutlookSignature:async()=>({html:'',attachments:[]}),outlookDraftComposeLink:x=>x,addSmallOutlookAttachment:async()=>{calls.push('attachment');if(attachmentFailure)throw new Error('upload failed')},addLargeOutlookAttachment:async()=>{calls.push('large attachment')},deleteOutlookDraft:async()=>calls.push('delete'),SIMPLE_ATTACHMENT_MAX_SIZE:100,OutlookReconnectRequiredError:class extends Error{},fetch:async url=>{if(url.endsWith('/send')){calls.push('send');if(networkFailure)throw new Error('network');return {status:sendStatus};}calls.push('create');return {ok:true,status:201,json:async()=>({id:'message',webLink:'draft-link'})}}};
 const mod={exports:{}};new Function('exports',...Object.keys(deps),code)(mod.exports,...Object.values(deps));return {send:options=>mod.exports.createOutlookDraft({},'user',{recipientEmail:'test@example.test',subject:'Subject',htmlBody:'Body',...options}),calls};
}
test('direct sending waits for all attachments and returns sent folder only after 202',async()=>{const c=setup();assert.match(await c.send({sendImmediately:true,attachments:[{fileContent:Buffer.from('pdf')},{fileContent:Buffer.alloc(200)}]}),/sentitems/);assert.deepEqual(c.calls,['create','attachment','large attachment','send']);});
test('missing send consent and failed uploads do not send mail',async()=>{let c=setup({scope:'Mail.ReadWrite'});await assert.rejects(c.send({sendImmediately:true}),/opnieuw/);assert.deepEqual(c.calls,[]);c=setup({attachmentFailure:true});await assert.rejects(c.send({sendImmediately:true,attachments:[{fileContent:Buffer.from('pdf')}]}));assert.deepEqual(c.calls,['create','attachment','delete']);});
test('known rejection is not success; uncertain outcome is never retried',async()=>{let c=setup({sendStatus:403});await assert.rejects(c.send({sendImmediately:true}),/opnieuw/);assert.deepEqual(c.calls,['create','send','delete']);c=setup({networkFailure:true});await assert.rejects(c.send({sendImmediately:true}),/verzendstatus is onbekend/);assert.deepEqual(c.calls,['create','send']);});
test('legacy draft clients keep creating drafts without unexpectedly sending',async()=>{const c=setup({scope:'Mail.ReadWrite'});assert.equal(await c.send({}),'draft-link');assert.deepEqual(c.calls,['create']);});
