"use client";
import {useEffect,useState} from "react";
export default function DealFulfillmentPanel({dealId,accepted,amount,canOrder,onSaved}:{dealId:string;accepted:boolean;amount:number;canOrder:boolean;onSaved:()=>void}){
 const [name,setName]=useState("");const [date,setDate]=useState("");const [orderId,setOrderId]=useState("");const [pending,setPending]=useState(false);const [loaded,setLoaded]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [preview,setPreview]=useState<{lines:{description:string;quantity:string;price:string}[];total:number}|null>(null);
 useEffect(()=>{const controller=new AbortController();void fetch(`/api/deals/${dealId}/assets`,{signal:controller.signal}).then(r=>r.json()).then(d=>{if(controller.signal.aborted)return;setName(d.overview?.administrationName??"");setDate(d.overview?.plannedGoLiveDate??"");}).catch(()=>{});
 if(canOrder)void fetch(`/api/deals/${dealId}/order`,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(controller.signal.aborted)return;setOrderId(d.orderId??"");setPending(Boolean(d.pending));setLoaded(true);}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return()=>controller.abort();},[dealId,canOrder]);
 async function run(action:"settings"|"preview"|"create"){
 setBusy(true);setMessage("");try{const response=await fetch(`/api/deals/${dealId}/${action==="settings"?"assets":"order"}`,{method:action==="settings"?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action==="settings"?{administrationName:name,startDate:date}:{mode:action})});const data=await response.json();if(!response.ok)throw new Error(data.error);if(action==="preview")setPreview(data);if(action==="create"){setOrderId(data.orderId);setPreview(null);}setMessage(action==="settings"?"Startgegevens opgeslagen.":action==="create"?`Order ${data.orderId} aangemaakt.`:"");onSaved();}catch(error){setMessage(error instanceof Error?error.message:"Verwerken mislukt.");if(action==="create"){setPending(true);setPreview(null);}}finally{setBusy(false);}}
 return <section className="card panel"><h2>Goedgekeurde deal verwerken</h2><p>Stel de startgegevens voor de nieuwe assets in. Maak voor eenmalige implementatiekosten een order aan.</p>
 <div className="button-row" style={{alignItems:"end",flexWrap:"wrap"}}><label>Administratienaam<input className="input" value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>Startdatum assets<input className="input" type="date" value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/></label><button className="secondary-button" disabled={busy||!name||!date} onClick={()=>void run("settings")}>Startgegevens opslaan</button></div>
 <h3>Order</h3>{orderId?<p>Order {orderId} aangemaakt.</p>:amount<=0?<p>Geen eenmalige kosten: er is geen order nodig.</p>:<><button className="secondary-button" disabled={!accepted||!canOrder||!loaded||pending||busy} onClick={()=>void run("preview")}>Order controleren</button>{pending?<p>Controleer de eerdere orderpoging in Smart Trade.</p>:null}{preview?<div><ul>{preview.lines.map((line,i)=><li key={i}>{line.description} · {line.quantity} × € {line.price}</li>)}</ul><p>Totaal € {preview.total.toFixed(2)}</p><button className="primary-button" disabled={busy||!accepted} onClick={()=>void run("create")}>Order aanmaken in Smart Trade</button></div>:null}</>}
 {!accepted?<p>De klant moet eerst akkoord geven voordat de deal verwerkt kan worden.</p>:null}<p role="status">{message}</p></section>;
}
